<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\MaintainXpert.SharedKernel\MaintainXpert.SharedKernel.csproj" />
    <ProjectReference Include="..\MaintainXpert.Maintenance\MaintainXpert.Maintenance.csproj" />
    <ProjectReference Include="..\MaintainXpert.Assets\MaintainXpert.Assets.csproj" />
    <ProjectReference Include="..\MaintainXpert.Notifications\MaintainXpert.Notifications.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" Version="10.2.3" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3df6eb4e-0e2f-4ce9-a35f-e6b1f69594da</UserSecretsId>
  </PropertyGroup>

</Project>
